substitutions:
  name: apollo-mtr-1
  version: "24.7.6.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

captive_portal:

web_server:
  port: 80

api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"

    #Co2 Calibration Service
    - service: calibrate_co2_value
      variables:
        co2_ppm: float
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda "return co2_ppm;"
            id: scd40