esphome:
  name: "${name}"
  friendly_name: Apollo MTR-1
  comment: Apollo MTR-1
  name_add_mac_suffix: true

  project:
    name: "ApolloAutomation.MTR-1"
    version: "${version}"

  min_version: 2025.8.0
  on_boot:
  - priority: 500
    then:
      - text_sensor.template.publish:
          id: apollo_firmware_version
          state: "${version}"
  - priority: -10
    then:
      - if:
          condition:
            - lambda: "return id(runTest);"
          then:
            - lambda: "id(testScript).execute();"

logger:

dashboard_import:
  package_import_url: github://ApolloAutomation/MTR-1/Integrations/ESPHome/MTR-1.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_default
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://apolloautomation.github.io/MTR-1/firmware/manifest.json

wifi:
  power_save_mode: none
  ap:
    ssid: "Apollo MTR1 Hotspot"
    
packages:
  core: !include Core.yaml
